### ISSUE TITLE
condition="application/xml" not in response.headers

### ISSUE THREAD

**Issue by jdubz666** [emcniece/bchydro#24]
Hi @emcniece 

Hope all is well!

It looks like something broke for my BC Hydro data pull. I'm receiving the error below. 

It looks like I've received this since May 3, 2022.

Are you receiving this?  Or have any ideas?

Thanks!

Traceback (most recent call last):
  File "/home/pi/bchydro/daily.py", line 82, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/bchydro/daily.py", line 40, in main
    usage = await a.get_usage(hourly=False)
  File "/home/pi/bchydro/bchydro/api.py", line 296, in get_usage
    await self._refresh_if(not self.usage, hourly=hourly)
  File "/home/pi/bchydro/bchydro/api.py", line 125, in _refresh_if
    await self.refresh(hourly=hourly)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/pi/.local/lib/python3.7/site-packages/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/home/pi/bchydro/bchydro/api.py", line 230, in refresh
    condition="application/xml" not in response.headers["content-type"],
KeyError: 'content-type'

**Comment by emcniece** [comment]
Haven't seen this yet, because I'm not using this project 😓 

Looks like the server responses changed something - I'll add this to the list. Thanks for reporting!

**Comment by jdubz666** [comment]
Thank you!!

**Comment by emcniece** [comment]
Well, this library might be dead. One of the worst-case scenarios has happened: BCHydro implemented Google ReCaptcha.

Authentication is failing because Python is not rendering Javascript, which leaves the `g-recaptcha-response` input empty during login.

ReCaptcha is designed to thwart bots and scripts like this. We might be able to get around it by using a headless browser, but I suspect ReCaptcha will detect this too.

**Comment by emcniece** [comment]
An evening of testing has demonstrated that https://github.com/pyppeteer/pyppeteer can successfully log in! There are some other cookie/CSRF issues though. I might be able to rewrite a large chunk of this library, but there may be longer waits to fetch data.

**Comment by msadatsafavi** [comment]
Thanks for your work on this. BC Hydro should implement a proper API system before thwarting users.

Good luck and happy to test too.

**Comment by emcniece** [comment]
Thanks for the support, team. Do either of you have multiple properties inside your BCHydro account?

**Comment by jdubz666** [comment]
Sorry I only have one property address under my account. 

Maybe I could link it to family members account if needed.

**Comment by msadatsafavi** [comment]
Hi Eric,

I do – but was working on this using a read-only account connected to one.

Happy to test with the other one that has two properties on it.

**Comment by emcniece** [comment]
Ok excellent, thank you!

I've been working on this every night this week, and I'll soon have a branch up for testing. Stay tuned 📻

**Comment by msadatsafavi** [comment]
Thanks for your hard work. We (and BC Hydro) owe you a big one. 

I see a project for bchydro @ HASS. This is great. Happy to test that one too!
